version: "3.9"
services:
#  frontend:
#    build: ./frontend
#    ports:
#      - "80:5000"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
  
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "/usr/bin/pg_isready"
      interval: 5s
      timeout: 10s
      retries: 120
