import '@/styles/globals.css';
import Layout from '@/components/Layout';
import { UserProvider } from '@/app/context/UserContext';
import Head from 'next/head';

export default function App({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Bell Challenge</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <UserProvider
          name='John Doe'
          score={3}
          role='Developer'
          workplace='Acme Inc.'
        >
          <Component {...pageProps} />
        </UserProvider>
      </Layout>
    </div>
  );
}
